new version

diff --git a/.github/workflows/Azure.yml b/.github/workflows/Azure.yml
--- a/.github/workflows/Azure.yml
+++ b/.github/workflows/Azure.yml
@@ -98,8 +98,8 @@ jobs:
 
   terraform-plan:
     name: Terraform Plan
-    if: always()
-    #if: ${{ github.event_name == 'pull_request' || ( github.event.issue.pull_request && ( contains(github.event.comment.body, 'terraform plan') || contains(github.event.comment.body, 'terraform apply') ) ) }}
+#    if: always()
+    if: ${{ github.event_name == 'pull_request' || ( github.event.issue.pull_request && ( contains(github.event.comment.body, 'terraform plan') ) }}
     runs-on: ubuntu-latest
     needs: [terraform-fmt, terraform-validate]
     env:
@@ -109,9 +109,9 @@ jobs:
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}               # Can be configured in Terraform Cloud
     steps:
 
-      - name: Validate Needs
-        if: ${{ needs.terraform-fmt.result == 'failure' || needs.terraform-validate.result == 'failure' }}
-        run: exit 1
+#      - name: Validate Needs
+#        if: ${{ needs.terraform-fmt.result == 'failure' || needs.terraform-validate.result == 'failure' }}
+#        run: exit 1
       
       - name: Checkout
         uses: actions/checkout@v3
@@ -137,6 +137,7 @@ jobs:
     name: "Pull Request Review"
     if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
     runs-on: ubuntu-latest
+    needs: terraform-plan
     steps:
       - run: echo "Approved"
 
@@ -144,7 +145,7 @@ jobs:
     name: Terraform Apply
     if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply') }}
     runs-on: ubuntu-latest
-    needs: [terraform-plan,review]
+    needs: review
     env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}               # Can be configured in Terraform Cloud
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}       # Can be configured in Terraform Cloud
@@ -152,9 +153,9 @@ jobs:
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}               # Can be configured in Terraform Cloud
     steps:
 
-      - name: Validate Needs
-        if: ${{ needs.review.result != 'success' }}
-        run: exit 1
+#      - name: Validate Needs
+#        if: ${{ needs.review.result != 'success' }}
+#        run: exit 1
 
       - name: Checkout
         uses: actions/checkout@v3
@@ -168,7 +169,14 @@ jobs:
       - name: Terraform Init
         id: init
         run: terraform init
-        
+
+      - name: Terraform Plan
+        id: plan
+        uses: benyboy84/GitHubAction_terraform-plan@v1.0.0
+        with:
+          GitHub_Token: ${{ secrets.GITHUB_TOKEN }}
+          Out: terraform.tfplan
+
       - name: Terraform Apply
         id: apply
         uses: benyboy84/GitHubAction_terraform-apply@v1.0.0
